# Generated by Django 4.2.7 on 2023-12-08 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('transferencia_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha_transferido', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transferencias',
                'managed': False,
            },
        ),
    ]
