# Generated by Django 4.2.7 on 2023-12-08 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Transferencias', '0002_alter_transferencia_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencia',
            options={'managed': False},
        ),
    ]
