# Generated by Django 4.2.7 on 2023-12-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transferencias', '0003_alter_transferencia_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('servicio_id', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('fecha_pagado', models.DateField(auto_now_add=True)),
                ('pagado', models.BooleanField()),
            ],
            options={
                'db_table': 'pagar_servicios',
                'managed': False,
            },
        ),
    ]
