# Generated by Django 4.2.7 on 2023-11-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarcaTarjeta',
            fields=[
                ('card_brand_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_brand', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'marca_tarjeta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_number', models.IntegerField(unique=True)),
                ('cvv', models.IntegerField()),
                ('emision_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('active', models.BooleanField()),
            ],
            options={
                'db_table': 'tarjeta',
                'managed': False,
            },
        ),
    ]
