# Generated by Django 4.2.7 on 2023-11-22 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djtriggers', '0008_alter_trigger_id_alter_triggerresult_id'),
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTrigger',
            fields=[
                ('trigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djtriggers.trigger')),
            ],
            bases=('djtriggers.trigger',),
        ),
    ]
