# Generated by Django 4.2.7 on 2023-12-06 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Cuentas', '0001_initial'),
        ('Clientes', '0001_initial'),
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('loan_type', models.TextField(verbose_name='Tipo de préstamo')),
                ('loan_total', models.IntegerField()),
                ('aproved', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Cuentas.cuenta')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.cliente')),
            ],
        ),
    ]
