# Generated by Django 4.2.7 on 2023-12-06 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0002_solicitudprestamo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudprestamo',
            options={'managed': False},
        ),
    ]
