# Generated by Django 4.2.7 on 2023-12-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0003_alter_solicitudprestamo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='solicitudprestamo',
            table='solicitud_prestamo',
        ),
    ]
