# Generated by Django 4.2.7 on 2023-12-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'direccion_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DireccionEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'direccion_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('direccion_id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_calle', models.CharField(max_length=50)),
                ('direccion_provincia', models.CharField(max_length=50)),
                ('direccion_pais', models.CharField(max_length=50)),
                ('direccion_codigo_postal', models.IntegerField()),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
    ]
